# gan model, PathChar_GAN,RPathChar_GAN,RGAN, CotGAN,NsdeGAN 
model_type: VAE
algo: TimeVAE
wandb_api:
train: True
pretrained: False
#generator: PathChar
model: TimeVAE

#dataset, ROUGH, MNIST, STOCK, BerkeleyMHAD, Air_Quality
dataset: ROUGH
# BerkeleyMHAD datatype: angles, keypoints
data_type: angles
num_classes: 3
conditional: False

device: cuda
seed: 0
gpu_id : "1"
# n_lags, length of the time series, STOCKs:20
n_lags: 50
#hyperparameters:
lr_G: 0.002
D_steps_per_G_step: 3
batch_size: 256
steps: 5


#vae hyperparameter:
G_input_dim: 5
latent_dim: 64
reconstruction_wt: 3.0
hidden_layer_sizes: [64, 64]

#decoder hyperparameter:
trend_poly: 0
num_gen_seas: 0
custom_seas: 
use_scaler: False
use_residual_conn: True





### ADDED FOR COMPABILITY

#generator hyperparameter:
G_hidden_dim: 64 
G_num_layers: 2

#discriminator hyperparameter:
D_hidden_dim: 64
D_num_layers: 3
D_out_dim: 5

comment: 

