# gan model, PathChar_GAN,RPathChar_GAN,RGAN,TimeGAN, CotGAN
model_type: GAN
algo: TimeGAN  
wandb_api: 
train: True
pretrained: False
#generator: PathChar
generator: LSTM
#discrimator:
discriminator: LSTM
#dataset, ROUGH, MNIST, STOCK, BerkeleyMHAD, Air_Quality
dataset: ROUGH
conditional: False

device: cuda
seed: 0
gpu_id : "1"
# n_lags, length of the time series, STOCKs:20
n_lags: 50
#hyperparameters:
lr_G: 0.002
lr_D: 0.003
D_steps_per_G_step: 3
batch_size: 256
steps: 10
#generator hyperparameter:
G_input_dim: 5
G_hidden_dim: 64 
G_num_layers: 2
init_fixed: False
#discriminator hyperparameter:
D_hidden_dim: 64
D_num_layers: 3
D_out_dim: 5
# config for PathChar_GAN
M_hidden_dim: 10
M_num_samples: 10
lr_M: 0.002
Lambda: 0
add_time: True
include_D: False

comment: 

